# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILE_COLLECTIONS += "datra-layer"
BBFILE_PATTERN_datra-layer := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_datra-layer = "honister kirkstone langdale mickledore nanbield scarthgap"
